export const SetTheorySymbols = {
  ELEMENT_OF: {
    label: "∈",
    description: "Element of",
    latex: "\\in",
    backgroundColor: "bg-slate-900",
  },
  NOT_ELEMENT_OF: {
    label: "∉",
    description: "Not element of",
    latex: "\\notin",
    backgroundColor: "bg-slate-900",
  },
  SUBSET: {
    label: "⊆",
    description: "Subset",
    latex: "\\subseteq",
    backgroundColor: "bg-slate-900",
  },
  PROPER_SUBSET: {
    label: "⊂",
    description: "Proper subset",
    latex: "\\subset",
    backgroundColor: "bg-slate-900",
  },
  SUPERSET: {
    label: "⊇",
    description: "Superset",
    latex: "\\supseteq",
    backgroundColor: "bg-slate-900",
  },
  PROPER_SUPERSET: {
    label: "⊃",
    description: "Proper superset",
    latex: "\\supset",
    backgroundColor: "bg-slate-900",
  },
  EMPTY_SET: {
    label: "∅",
    description: "Empty set",
    latex: "\\emptyset",
    backgroundColor: "bg-slate-900",
  },
  NATURAL_NUMBERS: {
    label: "ℕ",
    description: "Natural numbers",
    latex: "\\mathbb{N}",
    backgroundColor: "bg-slate-900",
  },
  INTEGERS: {
    label: "ℤ",
    description: "Integers",
    latex: "\\mathbb{Z}",
    backgroundColor: "bg-slate-900",
  },
  RATIONALS: {
    label: "ℚ",
    description: "Rationals",
    latex: "\\mathbb{Q}",
    backgroundColor: "bg-slate-900",
  },
  REALS: {
    label: "ℝ",
    description: "Reals",
    latex: "\\mathbb{R}",
    backgroundColor: "bg-slate-900",
  },
  COMPLEX_NUMBERS: {
    label: "ℂ",
    description: "Complex numbers",
    latex: "\\mathbb{C}",
    backgroundColor: "bg-slate-900",
  },
  UNION: {
    label: "∪",
    description: "Union",
    latex: "\\cup",
    backgroundColor: "bg-slate-900",
  },
  INTERSECTION: {
    label: "∩",
    description: "Intersection",
    latex: "\\cap",
    backgroundColor: "bg-slate-900",
  },
  SET_DIFFERENCE: {
    label: "\\setminus",
    description: "Set difference",
    latex: "\\setminus",
    backgroundColor: "bg-slate-900",
  },
  NOT_SUBSET: {
    label: "⊈",
    description: "Not subset",
    latex: "\\nsubseteq",
    backgroundColor: "bg-slate-900",
  },
  CARTESIAN_PRODUCT: {
    label: "×",
    description: "Cartesian product",
    latex: "\\times",
    backgroundColor: "bg-slate-900",
  },
  POWER_SET: {
    label: "P(A)",
    description: "Power set",
    latex: "\\mathcal{P}(A)",
    backgroundColor: "bg-slate-900",
  },
};
